version: '3.8'

services:
  web:
    build: .
    image: project:0.1
    container_name: project
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - project
  db:
    image: postgres:15.3
    container_name: project-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - project

volumes:
  postgres_data:

networks:
  project:
    name: project_network
